# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: s1mulado_db
      POSTGRES_USER: user          
      POSTGRES_PASSWORD: password      
      POSTGRES_HOST_AUTH_METHOD: trust
      PGSSLMODE: disable
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/entrypoint:/docker-entrypoint-initdb.d
volumes:
  pgdata:
